Trivial fix.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,9 +1,15 @@
-#!/bin/bash -e
+#!/bin/bash
+
+set -e
 
 : ${CONSUL_HOME:=/home/vagrant/consul}
 : ${CONSUL_BIN_DIR:=${CONSUL_HOME}/bin}
+
 CONSUL_VERSION=0.6.3
 CONSUL_ZIP=/tmp/consul.zip
+
+# Cleanup hook
+trap "rm ${CONSUL_ZIP}" EXIT
 
 # Setup
 mkdir -p ${CONSUL_HOME} ${CONSUL_BIN_DIR}
@@ -22,6 +28,3 @@ chmod +x ${CONSUL_BIN_DIR}/consul
 # Test
 ${CONSUL_BIN_DIR}/consul --version | grep -q ${CONSUL_VERSION}
 echo Installation Success.
-
-# Cleanup
-trap "rm ${CONSUL_ZIP}" EXIT
